/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeatureRouteImport } from './routes/feature'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as Student_v2RouteRouteImport } from './routes/_student_v2/route'
import { Route as MentorRouteRouteImport } from './routes/_mentor/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as Student_v2WorkspaceRouteImport } from './routes/_student_v2/workspace'
import { Route as Student_v2ProjectHubRouteImport } from './routes/_student_v2/project-hub'
import { Route as Student_v2PortofolioRouteImport } from './routes/_student_v2/portofolio'
import { Route as Student_v2OverviewRouteImport } from './routes/_student_v2/overview'
import { Route as MentorNewProjectRouteImport } from './routes/_mentor/new-project'
import { Route as MentorGlobalOverviewRouteImport } from './routes/_mentor/global-overview'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminTemplatesRouteImport } from './routes/_admin/templates'
import { Route as AdminRolesRouteImport } from './routes/_admin/roles'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminBillingRouteImport } from './routes/_admin/billing'
import { Route as AdminAuditRouteImport } from './routes/_admin/audit'
import { Route as AdminAiStatsRouteImport } from './routes/_admin/ai-stats'
import { Route as Student_v2Project_idRouteRouteImport } from './routes/_student_v2/$project_id/route'
import { Route as MentorProjectIdRouteRouteImport } from './routes/_mentor/$projectId/route'
import { Route as Student_v2Project_idRadarHealthRouteImport } from './routes/_student_v2/$project_id/radar-health'
import { Route as Student_v2Project_idMissionLabRouteImport } from './routes/_student_v2/$project_id/mission-lab'
import { Route as Student_v2Project_idLearningPathRouteImport } from './routes/_student_v2/$project_id/learning-path'
import { Route as Student_v2Project_idDiscussionRoomRouteImport } from './routes/_student_v2/$project_id/discussion-room'
import { Route as Student_v2Project_idAchievementRouteImport } from './routes/_student_v2/$project_id/achievement'
import { Route as MentorProjectIdStudentRadarRouteImport } from './routes/_mentor/$projectId/student-radar'
import { Route as MentorProjectIdReviewQueueRouteImport } from './routes/_mentor/$projectId/review-queue'
import { Route as MentorProjectIdParticipantsRouteImport } from './routes/_mentor/$projectId/participants'
import { Route as MentorProjectIdCourseBuilderRouteImport } from './routes/_mentor/$projectId/course-builder'
import { Route as MentorProjectIdAnalyticsRouteImport } from './routes/_mentor/$projectId/analytics'
import { Route as MentorProjectIdAiConfigRouteImport } from './routes/_mentor/$projectId/ai-config'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureRoute = FeatureRouteImport.update({
  id: '/feature',
  path: '/feature',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Student_v2RouteRoute = Student_v2RouteRouteImport.update({
  id: '/_student_v2',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRouteRoute = MentorRouteRouteImport.update({
  id: '/_mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const Student_v2WorkspaceRoute = Student_v2WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => Student_v2RouteRoute,
} as any)
const Student_v2ProjectHubRoute = Student_v2ProjectHubRouteImport.update({
  id: '/project-hub',
  path: '/project-hub',
  getParentRoute: () => Student_v2RouteRoute,
} as any)
const Student_v2PortofolioRoute = Student_v2PortofolioRouteImport.update({
  id: '/portofolio',
  path: '/portofolio',
  getParentRoute: () => Student_v2RouteRoute,
} as any)
const Student_v2OverviewRoute = Student_v2OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => Student_v2RouteRoute,
} as any)
const MentorNewProjectRoute = MentorNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => MentorRouteRoute,
} as any)
const MentorGlobalOverviewRoute = MentorGlobalOverviewRouteImport.update({
  id: '/global-overview',
  path: '/global-overview',
  getParentRoute: () => MentorRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiStatsRoute = AdminAiStatsRouteImport.update({
  id: '/ai-stats',
  path: '/ai-stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Student_v2Project_idRouteRoute =
  Student_v2Project_idRouteRouteImport.update({
    id: '/$project_id',
    path: '/$project_id',
    getParentRoute: () => Student_v2RouteRoute,
  } as any)
const MentorProjectIdRouteRoute = MentorProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => MentorRouteRoute,
} as any)
const Student_v2Project_idRadarHealthRoute =
  Student_v2Project_idRadarHealthRouteImport.update({
    id: '/radar-health',
    path: '/radar-health',
    getParentRoute: () => Student_v2Project_idRouteRoute,
  } as any)
const Student_v2Project_idMissionLabRoute =
  Student_v2Project_idMissionLabRouteImport.update({
    id: '/mission-lab',
    path: '/mission-lab',
    getParentRoute: () => Student_v2Project_idRouteRoute,
  } as any)
const Student_v2Project_idLearningPathRoute =
  Student_v2Project_idLearningPathRouteImport.update({
    id: '/learning-path',
    path: '/learning-path',
    getParentRoute: () => Student_v2Project_idRouteRoute,
  } as any)
const Student_v2Project_idDiscussionRoomRoute =
  Student_v2Project_idDiscussionRoomRouteImport.update({
    id: '/discussion-room',
    path: '/discussion-room',
    getParentRoute: () => Student_v2Project_idRouteRoute,
  } as any)
const Student_v2Project_idAchievementRoute =
  Student_v2Project_idAchievementRouteImport.update({
    id: '/achievement',
    path: '/achievement',
    getParentRoute: () => Student_v2Project_idRouteRoute,
  } as any)
const MentorProjectIdStudentRadarRoute =
  MentorProjectIdStudentRadarRouteImport.update({
    id: '/student-radar',
    path: '/student-radar',
    getParentRoute: () => MentorProjectIdRouteRoute,
  } as any)
const MentorProjectIdReviewQueueRoute =
  MentorProjectIdReviewQueueRouteImport.update({
    id: '/review-queue',
    path: '/review-queue',
    getParentRoute: () => MentorProjectIdRouteRoute,
  } as any)
const MentorProjectIdParticipantsRoute =
  MentorProjectIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => MentorProjectIdRouteRoute,
  } as any)
const MentorProjectIdCourseBuilderRoute =
  MentorProjectIdCourseBuilderRouteImport.update({
    id: '/course-builder',
    path: '/course-builder',
    getParentRoute: () => MentorProjectIdRouteRoute,
  } as any)
const MentorProjectIdAnalyticsRoute =
  MentorProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => MentorProjectIdRouteRoute,
  } as any)
const MentorProjectIdAiConfigRoute = MentorProjectIdAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => MentorProjectIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/feature': typeof FeatureRoute
  '/pricing': typeof PricingRoute
  '/showcase': typeof ShowcaseRoute
  '/$projectId': typeof MentorProjectIdRouteRouteWithChildren
  '/$project_id': typeof Student_v2Project_idRouteRouteWithChildren
  '/ai-stats': typeof AdminAiStatsRoute
  '/audit': typeof AdminAuditRoute
  '/billing': typeof AdminBillingRoute
  '/dashboard': typeof AdminDashboardRoute
  '/roles': typeof AdminRolesRoute
  '/templates': typeof AdminTemplatesRoute
  '/users': typeof AdminUsersRoute
  '/global-overview': typeof MentorGlobalOverviewRoute
  '/new-project': typeof MentorNewProjectRoute
  '/overview': typeof Student_v2OverviewRoute
  '/portofolio': typeof Student_v2PortofolioRoute
  '/project-hub': typeof Student_v2ProjectHubRoute
  '/workspace': typeof Student_v2WorkspaceRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$projectId/ai-config': typeof MentorProjectIdAiConfigRoute
  '/$projectId/analytics': typeof MentorProjectIdAnalyticsRoute
  '/$projectId/course-builder': typeof MentorProjectIdCourseBuilderRoute
  '/$projectId/participants': typeof MentorProjectIdParticipantsRoute
  '/$projectId/review-queue': typeof MentorProjectIdReviewQueueRoute
  '/$projectId/student-radar': typeof MentorProjectIdStudentRadarRoute
  '/$project_id/achievement': typeof Student_v2Project_idAchievementRoute
  '/$project_id/discussion-room': typeof Student_v2Project_idDiscussionRoomRoute
  '/$project_id/learning-path': typeof Student_v2Project_idLearningPathRoute
  '/$project_id/mission-lab': typeof Student_v2Project_idMissionLabRoute
  '/$project_id/radar-health': typeof Student_v2Project_idRadarHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/feature': typeof FeatureRoute
  '/pricing': typeof PricingRoute
  '/showcase': typeof ShowcaseRoute
  '/$projectId': typeof MentorProjectIdRouteRouteWithChildren
  '/$project_id': typeof Student_v2Project_idRouteRouteWithChildren
  '/ai-stats': typeof AdminAiStatsRoute
  '/audit': typeof AdminAuditRoute
  '/billing': typeof AdminBillingRoute
  '/dashboard': typeof AdminDashboardRoute
  '/roles': typeof AdminRolesRoute
  '/templates': typeof AdminTemplatesRoute
  '/users': typeof AdminUsersRoute
  '/global-overview': typeof MentorGlobalOverviewRoute
  '/new-project': typeof MentorNewProjectRoute
  '/overview': typeof Student_v2OverviewRoute
  '/portofolio': typeof Student_v2PortofolioRoute
  '/project-hub': typeof Student_v2ProjectHubRoute
  '/workspace': typeof Student_v2WorkspaceRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/$projectId/ai-config': typeof MentorProjectIdAiConfigRoute
  '/$projectId/analytics': typeof MentorProjectIdAnalyticsRoute
  '/$projectId/course-builder': typeof MentorProjectIdCourseBuilderRoute
  '/$projectId/participants': typeof MentorProjectIdParticipantsRoute
  '/$projectId/review-queue': typeof MentorProjectIdReviewQueueRoute
  '/$projectId/student-radar': typeof MentorProjectIdStudentRadarRoute
  '/$project_id/achievement': typeof Student_v2Project_idAchievementRoute
  '/$project_id/discussion-room': typeof Student_v2Project_idDiscussionRoomRoute
  '/$project_id/learning-path': typeof Student_v2Project_idLearningPathRoute
  '/$project_id/mission-lab': typeof Student_v2Project_idMissionLabRoute
  '/$project_id/radar-health': typeof Student_v2Project_idRadarHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_mentor': typeof MentorRouteRouteWithChildren
  '/_student_v2': typeof Student_v2RouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/feature': typeof FeatureRoute
  '/pricing': typeof PricingRoute
  '/showcase': typeof ShowcaseRoute
  '/_mentor/$projectId': typeof MentorProjectIdRouteRouteWithChildren
  '/_student_v2/$project_id': typeof Student_v2Project_idRouteRouteWithChildren
  '/_admin/ai-stats': typeof AdminAiStatsRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/billing': typeof AdminBillingRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/roles': typeof AdminRolesRoute
  '/_admin/templates': typeof AdminTemplatesRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_mentor/global-overview': typeof MentorGlobalOverviewRoute
  '/_mentor/new-project': typeof MentorNewProjectRoute
  '/_student_v2/overview': typeof Student_v2OverviewRoute
  '/_student_v2/portofolio': typeof Student_v2PortofolioRoute
  '/_student_v2/project-hub': typeof Student_v2ProjectHubRoute
  '/_student_v2/workspace': typeof Student_v2WorkspaceRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_mentor/$projectId/ai-config': typeof MentorProjectIdAiConfigRoute
  '/_mentor/$projectId/analytics': typeof MentorProjectIdAnalyticsRoute
  '/_mentor/$projectId/course-builder': typeof MentorProjectIdCourseBuilderRoute
  '/_mentor/$projectId/participants': typeof MentorProjectIdParticipantsRoute
  '/_mentor/$projectId/review-queue': typeof MentorProjectIdReviewQueueRoute
  '/_mentor/$projectId/student-radar': typeof MentorProjectIdStudentRadarRoute
  '/_student_v2/$project_id/achievement': typeof Student_v2Project_idAchievementRoute
  '/_student_v2/$project_id/discussion-room': typeof Student_v2Project_idDiscussionRoomRoute
  '/_student_v2/$project_id/learning-path': typeof Student_v2Project_idLearningPathRoute
  '/_student_v2/$project_id/mission-lab': typeof Student_v2Project_idMissionLabRoute
  '/_student_v2/$project_id/radar-health': typeof Student_v2Project_idRadarHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/feature'
    | '/pricing'
    | '/showcase'
    | '/$projectId'
    | '/$project_id'
    | '/ai-stats'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/roles'
    | '/templates'
    | '/users'
    | '/global-overview'
    | '/new-project'
    | '/overview'
    | '/portofolio'
    | '/project-hub'
    | '/workspace'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/$projectId/ai-config'
    | '/$projectId/analytics'
    | '/$projectId/course-builder'
    | '/$projectId/participants'
    | '/$projectId/review-queue'
    | '/$projectId/student-radar'
    | '/$project_id/achievement'
    | '/$project_id/discussion-room'
    | '/$project_id/learning-path'
    | '/$project_id/mission-lab'
    | '/$project_id/radar-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/feature'
    | '/pricing'
    | '/showcase'
    | '/$projectId'
    | '/$project_id'
    | '/ai-stats'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/roles'
    | '/templates'
    | '/users'
    | '/global-overview'
    | '/new-project'
    | '/overview'
    | '/portofolio'
    | '/project-hub'
    | '/workspace'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/$projectId/ai-config'
    | '/$projectId/analytics'
    | '/$projectId/course-builder'
    | '/$projectId/participants'
    | '/$projectId/review-queue'
    | '/$projectId/student-radar'
    | '/$project_id/achievement'
    | '/$project_id/discussion-room'
    | '/$project_id/learning-path'
    | '/$project_id/mission-lab'
    | '/$project_id/radar-health'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_mentor'
    | '/_student_v2'
    | '/contact'
    | '/feature'
    | '/pricing'
    | '/showcase'
    | '/_mentor/$projectId'
    | '/_student_v2/$project_id'
    | '/_admin/ai-stats'
    | '/_admin/audit'
    | '/_admin/billing'
    | '/_admin/dashboard'
    | '/_admin/roles'
    | '/_admin/templates'
    | '/_admin/users'
    | '/_mentor/global-overview'
    | '/_mentor/new-project'
    | '/_student_v2/overview'
    | '/_student_v2/portofolio'
    | '/_student_v2/project-hub'
    | '/_student_v2/workspace'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/_mentor/$projectId/ai-config'
    | '/_mentor/$projectId/analytics'
    | '/_mentor/$projectId/course-builder'
    | '/_mentor/$projectId/participants'
    | '/_mentor/$projectId/review-queue'
    | '/_mentor/$projectId/student-radar'
    | '/_student_v2/$project_id/achievement'
    | '/_student_v2/$project_id/discussion-room'
    | '/_student_v2/$project_id/learning-path'
    | '/_student_v2/$project_id/mission-lab'
    | '/_student_v2/$project_id/radar-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MentorRouteRoute: typeof MentorRouteRouteWithChildren
  Student_v2RouteRoute: typeof Student_v2RouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeatureRoute: typeof FeatureRoute
  PricingRoute: typeof PricingRoute
  ShowcaseRoute: typeof ShowcaseRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature': {
      id: '/feature'
      path: '/feature'
      fullPath: '/feature'
      preLoaderRoute: typeof FeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student_v2': {
      id: '/_student_v2'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Student_v2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mentor': {
      id: '/_mentor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MentorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student_v2/workspace': {
      id: '/_student_v2/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof Student_v2WorkspaceRouteImport
      parentRoute: typeof Student_v2RouteRoute
    }
    '/_student_v2/project-hub': {
      id: '/_student_v2/project-hub'
      path: '/project-hub'
      fullPath: '/project-hub'
      preLoaderRoute: typeof Student_v2ProjectHubRouteImport
      parentRoute: typeof Student_v2RouteRoute
    }
    '/_student_v2/portofolio': {
      id: '/_student_v2/portofolio'
      path: '/portofolio'
      fullPath: '/portofolio'
      preLoaderRoute: typeof Student_v2PortofolioRouteImport
      parentRoute: typeof Student_v2RouteRoute
    }
    '/_student_v2/overview': {
      id: '/_student_v2/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof Student_v2OverviewRouteImport
      parentRoute: typeof Student_v2RouteRoute
    }
    '/_mentor/new-project': {
      id: '/_mentor/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof MentorNewProjectRouteImport
      parentRoute: typeof MentorRouteRoute
    }
    '/_mentor/global-overview': {
      id: '/_mentor/global-overview'
      path: '/global-overview'
      fullPath: '/global-overview'
      preLoaderRoute: typeof MentorGlobalOverviewRouteImport
      parentRoute: typeof MentorRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/templates': {
      id: '/_admin/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/roles': {
      id: '/_admin/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/billing': {
      id: '/_admin/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/ai-stats': {
      id: '/_admin/ai-stats'
      path: '/ai-stats'
      fullPath: '/ai-stats'
      preLoaderRoute: typeof AdminAiStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_student_v2/$project_id': {
      id: '/_student_v2/$project_id'
      path: '/$project_id'
      fullPath: '/$project_id'
      preLoaderRoute: typeof Student_v2Project_idRouteRouteImport
      parentRoute: typeof Student_v2RouteRoute
    }
    '/_mentor/$projectId': {
      id: '/_mentor/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof MentorProjectIdRouteRouteImport
      parentRoute: typeof MentorRouteRoute
    }
    '/_student_v2/$project_id/radar-health': {
      id: '/_student_v2/$project_id/radar-health'
      path: '/radar-health'
      fullPath: '/$project_id/radar-health'
      preLoaderRoute: typeof Student_v2Project_idRadarHealthRouteImport
      parentRoute: typeof Student_v2Project_idRouteRoute
    }
    '/_student_v2/$project_id/mission-lab': {
      id: '/_student_v2/$project_id/mission-lab'
      path: '/mission-lab'
      fullPath: '/$project_id/mission-lab'
      preLoaderRoute: typeof Student_v2Project_idMissionLabRouteImport
      parentRoute: typeof Student_v2Project_idRouteRoute
    }
    '/_student_v2/$project_id/learning-path': {
      id: '/_student_v2/$project_id/learning-path'
      path: '/learning-path'
      fullPath: '/$project_id/learning-path'
      preLoaderRoute: typeof Student_v2Project_idLearningPathRouteImport
      parentRoute: typeof Student_v2Project_idRouteRoute
    }
    '/_student_v2/$project_id/discussion-room': {
      id: '/_student_v2/$project_id/discussion-room'
      path: '/discussion-room'
      fullPath: '/$project_id/discussion-room'
      preLoaderRoute: typeof Student_v2Project_idDiscussionRoomRouteImport
      parentRoute: typeof Student_v2Project_idRouteRoute
    }
    '/_student_v2/$project_id/achievement': {
      id: '/_student_v2/$project_id/achievement'
      path: '/achievement'
      fullPath: '/$project_id/achievement'
      preLoaderRoute: typeof Student_v2Project_idAchievementRouteImport
      parentRoute: typeof Student_v2Project_idRouteRoute
    }
    '/_mentor/$projectId/student-radar': {
      id: '/_mentor/$projectId/student-radar'
      path: '/student-radar'
      fullPath: '/$projectId/student-radar'
      preLoaderRoute: typeof MentorProjectIdStudentRadarRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
    '/_mentor/$projectId/review-queue': {
      id: '/_mentor/$projectId/review-queue'
      path: '/review-queue'
      fullPath: '/$projectId/review-queue'
      preLoaderRoute: typeof MentorProjectIdReviewQueueRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
    '/_mentor/$projectId/participants': {
      id: '/_mentor/$projectId/participants'
      path: '/participants'
      fullPath: '/$projectId/participants'
      preLoaderRoute: typeof MentorProjectIdParticipantsRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
    '/_mentor/$projectId/course-builder': {
      id: '/_mentor/$projectId/course-builder'
      path: '/course-builder'
      fullPath: '/$projectId/course-builder'
      preLoaderRoute: typeof MentorProjectIdCourseBuilderRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
    '/_mentor/$projectId/analytics': {
      id: '/_mentor/$projectId/analytics'
      path: '/analytics'
      fullPath: '/$projectId/analytics'
      preLoaderRoute: typeof MentorProjectIdAnalyticsRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
    '/_mentor/$projectId/ai-config': {
      id: '/_mentor/$projectId/ai-config'
      path: '/ai-config'
      fullPath: '/$projectId/ai-config'
      preLoaderRoute: typeof MentorProjectIdAiConfigRouteImport
      parentRoute: typeof MentorProjectIdRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAiStatsRoute: typeof AdminAiStatsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiStatsRoute: AdminAiStatsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MentorProjectIdRouteRouteChildren {
  MentorProjectIdAiConfigRoute: typeof MentorProjectIdAiConfigRoute
  MentorProjectIdAnalyticsRoute: typeof MentorProjectIdAnalyticsRoute
  MentorProjectIdCourseBuilderRoute: typeof MentorProjectIdCourseBuilderRoute
  MentorProjectIdParticipantsRoute: typeof MentorProjectIdParticipantsRoute
  MentorProjectIdReviewQueueRoute: typeof MentorProjectIdReviewQueueRoute
  MentorProjectIdStudentRadarRoute: typeof MentorProjectIdStudentRadarRoute
}

const MentorProjectIdRouteRouteChildren: MentorProjectIdRouteRouteChildren = {
  MentorProjectIdAiConfigRoute: MentorProjectIdAiConfigRoute,
  MentorProjectIdAnalyticsRoute: MentorProjectIdAnalyticsRoute,
  MentorProjectIdCourseBuilderRoute: MentorProjectIdCourseBuilderRoute,
  MentorProjectIdParticipantsRoute: MentorProjectIdParticipantsRoute,
  MentorProjectIdReviewQueueRoute: MentorProjectIdReviewQueueRoute,
  MentorProjectIdStudentRadarRoute: MentorProjectIdStudentRadarRoute,
}

const MentorProjectIdRouteRouteWithChildren =
  MentorProjectIdRouteRoute._addFileChildren(MentorProjectIdRouteRouteChildren)

interface MentorRouteRouteChildren {
  MentorProjectIdRouteRoute: typeof MentorProjectIdRouteRouteWithChildren
  MentorGlobalOverviewRoute: typeof MentorGlobalOverviewRoute
  MentorNewProjectRoute: typeof MentorNewProjectRoute
}

const MentorRouteRouteChildren: MentorRouteRouteChildren = {
  MentorProjectIdRouteRoute: MentorProjectIdRouteRouteWithChildren,
  MentorGlobalOverviewRoute: MentorGlobalOverviewRoute,
  MentorNewProjectRoute: MentorNewProjectRoute,
}

const MentorRouteRouteWithChildren = MentorRouteRoute._addFileChildren(
  MentorRouteRouteChildren,
)

interface Student_v2Project_idRouteRouteChildren {
  Student_v2Project_idAchievementRoute: typeof Student_v2Project_idAchievementRoute
  Student_v2Project_idDiscussionRoomRoute: typeof Student_v2Project_idDiscussionRoomRoute
  Student_v2Project_idLearningPathRoute: typeof Student_v2Project_idLearningPathRoute
  Student_v2Project_idMissionLabRoute: typeof Student_v2Project_idMissionLabRoute
  Student_v2Project_idRadarHealthRoute: typeof Student_v2Project_idRadarHealthRoute
}

const Student_v2Project_idRouteRouteChildren: Student_v2Project_idRouteRouteChildren =
  {
    Student_v2Project_idAchievementRoute: Student_v2Project_idAchievementRoute,
    Student_v2Project_idDiscussionRoomRoute:
      Student_v2Project_idDiscussionRoomRoute,
    Student_v2Project_idLearningPathRoute:
      Student_v2Project_idLearningPathRoute,
    Student_v2Project_idMissionLabRoute: Student_v2Project_idMissionLabRoute,
    Student_v2Project_idRadarHealthRoute: Student_v2Project_idRadarHealthRoute,
  }

const Student_v2Project_idRouteRouteWithChildren =
  Student_v2Project_idRouteRoute._addFileChildren(
    Student_v2Project_idRouteRouteChildren,
  )

interface Student_v2RouteRouteChildren {
  Student_v2Project_idRouteRoute: typeof Student_v2Project_idRouteRouteWithChildren
  Student_v2OverviewRoute: typeof Student_v2OverviewRoute
  Student_v2PortofolioRoute: typeof Student_v2PortofolioRoute
  Student_v2ProjectHubRoute: typeof Student_v2ProjectHubRoute
  Student_v2WorkspaceRoute: typeof Student_v2WorkspaceRoute
}

const Student_v2RouteRouteChildren: Student_v2RouteRouteChildren = {
  Student_v2Project_idRouteRoute: Student_v2Project_idRouteRouteWithChildren,
  Student_v2OverviewRoute: Student_v2OverviewRoute,
  Student_v2PortofolioRoute: Student_v2PortofolioRoute,
  Student_v2ProjectHubRoute: Student_v2ProjectHubRoute,
  Student_v2WorkspaceRoute: Student_v2WorkspaceRoute,
}

const Student_v2RouteRouteWithChildren = Student_v2RouteRoute._addFileChildren(
  Student_v2RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MentorRouteRoute: MentorRouteRouteWithChildren,
  Student_v2RouteRoute: Student_v2RouteRouteWithChildren,
  ContactRoute: ContactRoute,
  FeatureRoute: FeatureRoute,
  PricingRoute: PricingRoute,
  ShowcaseRoute: ShowcaseRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
